name: Package

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_call:

concurrency:
  group: package-${{ github.ref }}
  cancel-in-progress: true

jobs:
  package:
    name: Package
    runs-on: ubuntu-24.04

    steps:
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'

    - name: Check Python version
      run: |
        set -x
        python --version
        pip --version
        python -c "import platform; print(platform.architecture())"

    - name: Install Python dependencies
      run: |
        pip install --user setuptools wheel

    - name: Check out Kconfiglib source code
      uses: actions/checkout@v5

    - name: Build source distribution
      run: |
        python setup.py sdist

    - name: Build built distribution wheel
      run: |
        python setup.py bdist_wheel

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/*
