name: Style Check

on: [push, pull_request]

concurrency:
  group: style-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format-check:
    name: Check Code Format
    runs-on: ubuntu-latest

    steps:
    - name: Check out Kconfiglib source code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install tools
      run: |
           sudo apt-get install -q=2 shfmt python3-pip
           pip3 install black==25.1.0

    - name: Run format check
      run: |
           .ci/check-newline.sh
           .ci/check-format.sh
      shell: bash
